---
title: "eds223_week10"
format: html
editor_options: 
  chunk_output_type: console
---
```{r}
library(terra)
library(sf)
library(tidyverse)
library(tmap)
library(here)
library(ggplot2)
```

```{r}
# digital surface model
dsm <- rast(here("data","SJER2013_DSM.tif"))

# digital terrain model 
dtm <- rast(here("data","SJER2013_DTM.tif"))

test_raster <- c(dsm,dtm) # won't stack if crs, extent and res don't match

# create canopy height model
chm <- dsm - dtm 
```

## Load vegetation plot geometries

```{r}
plot_centroids <- st_read(here("data","PlotCentroids","SJERPlotCentroids_Buffer.shp")) %>%
  st_transform(., crs = st_crs(chm))
```

```{r}
tm_shape(chm) +
  tm_raster(title = "Canopy height model (m)") +
  tm_shape(plot_centroids) + 
  tm_polygons() +
  tm_layout(fontfamily = "courier")
```

## Load vegetation survey data

```{r}
veg_surveys <- read_csv(here("data","VegetationData","D17_2013_vegStr.csv")) %>%
  group_by(plotid) %>%
  summarize("survey_height" = max(stemheight, na.rm = TRUE))
```

```{r}
extract_chm_height <- terra::extract(chm, plot_centroids, fun = max) %>% # using max because same as used above 
  rename(chm_height = SJER2013_DSM) %>%
  select(chm_height)

plot_centroids <- cbind(plot_centroids, extract_chm_height) %>%
  left_join(., veg_surveys, by = c("Plot_ID" = "plotid")) # a way to bind even if col name not exact match!
  
```

```{r}
ggplot(plot_centroids, aes(x = chm_height, y = survey_height)) +
  geom_point() +
  geom_smooth(method = lm) +
  geom_abline(slope = 1, intercept = 0, alpha = 0.5, lty = 2) +
  xlab("Maximum measured height (lidar)") +
  ylab("Maximum measure height (survey)") +
  ggtitle("Validating lidar measurements") +
  theme_minimal() +
  theme(text = element_text(family = "courier"))
  
```











